import { useState } from 'react'
import { NavLink, useNavigate, useParams } from 'react-router-dom'
import { StageAvatar } from '../components/stage/StageAvatar'
import { StageButton } from '../components/stage/StageButton'
import { StageIcon } from '../components/stage/StageIcon'
import { artist, artists, conversations, dashboard, feedPosts, navigation, notifications } from '../data/demoData'
import rehearsalImage from '../assets/stage-pune-rehearsal.png'

function Sidebar() {
  return <aside className="workspace-sidebar">
    <NavLink to="/dashboard" className="workspace-brand">stage<span>.</span></NavLink>
    <NavLink to="/profile" className="profile-mini"><StageAvatar initials={artist.initials} /><div><strong>{artist.name}</strong><small>Artist account</small></div><span className="chevron">v</span></NavLink>
    <nav className="workspace-nav">{navigation.map(([path, label]) => <NavLink key={path} to={`/${path}`} className={({ isActive }) => `workspace-nav-item ${isActive ? 'active' : ''}`}><StageIcon name={path}/>{label}{path === 'messages' && <b>2</b>}</NavLink>)}</nav>
    <div className="sidebar-bottom"><NavLink to="/organization">Switch to organization</NavLink><NavLink to="/settings">Preferences</NavLink><NavLink className="logout-link" to="/">Log out</NavLink></div>
  </aside>
}

function Topbar() { return <header className="workspace-topbar"><NavLink to="/search" className="workspace-search"><StageIcon name="search" size={15}/><span>Search artists, roles, organizations...</span><kbd>CTRL K</kbd></NavLink><div className="topbar-actions"><NavLink to="/notifications" aria-label="Notifications"><StageIcon name="notifications" size={17}/><em /></NavLink><NavLink to="/profile"><StageAvatar initials={artist.initials} size="sm" /></NavLink></div></header> }

function PageTitle({ eyebrow, title, copy, action }) { return <div className="workspace-title-row"><div><p className="workspace-kicker">{eyebrow}</p><h1>{title}</h1>{copy && <p>{copy}</p>}</div>{action}</div> }

function Dashboard() { return <div className="workspace-content"><section className="rehearsal-hero"><img src={rehearsalImage} alt="Theatre artists rehearsing under warm stage lights"/><div className="rehearsal-hero-copy"><p>TONIGHT IN PUNE</p><h1>Make room<br/>for the work.</h1><span>Rehearsals, people, and new possibilities are already in motion.</span><NavLink to="/feed">Enter the community</NavLink></div><div className="rehearsal-stamp">PUNE<br/><i>THEATRE</i><br/>2026</div></section><PageTitle eyebrow="YOUR CREATIVE WORKSPACE" title={dashboard.greeting} copy={dashboard.summary} action={<NavLink to="/profile"><StageButton>Complete profile</StageButton></NavLink>} />
  <section className="workspace-grid"><div className="workspace-panel audition-panel"><div className="panel-heading"><div><p>UPCOMING</p><h2>Your auditions</h2></div><a href="#calendar">View calendar</a></div>{dashboard.auditions.map(a => <article className="audition-row" key={a.title}><time><strong>{a.day}</strong><span>{a.month}</span></time><div><h3>{a.title}</h3><p>{a.company}</p></div><span className="audition-time">{a.time}<small>{a.tag}</small></span><button className="more">More</button></article>)}</div>
  <aside className="profile-status"><div className="credit-orbit"><strong>{artist.completedCredits}</strong><span>verified<br />credits</span></div><h3>Your profile is looking good.</h3><p>One more detail will help organizations find you.</p><NavLink to="/profile">Add availability</NavLink></aside></section>
  <section className="workspace-panel opportunity-panel"><div className="panel-heading"><div><p>CURATED FOR YOU</p><h2>Roles worth a look</h2></div><NavLink to="/castings">View all roles</NavLink></div><div className="role-grid">{dashboard.opportunities.map(o => <article className="workspace-role" key={o.id}><span className={`role-mark ${o.tone}`}>ST</span><h3>{o.title}</h3><p>{o.company}</p><small>{o.meta}</small><NavLink to={`/castings?role=${o.id}`}>Open</NavLink></article>)}</div></section></div> }

function Feed() { const [posts, setPosts] = useState(feedPosts); const [draft, setDraft] = useState(''); const applaud = id => setPosts(posts.map(p => p.id === id ? { ...p, likes: p.likes + 1 } : p)); const publish = () => { if (!draft.trim()) return; setPosts([{ id: Date.now(), author: artist.name, initials: artist.initials, role: artist.role, time: 'now', text: draft, tags: ['pune-theatre'], likes: 0, comments: 0, color: 'orange' }, ...posts]); setDraft('') }
return <div className="workspace-content feed-page"><PageTitle eyebrow="PUNE THEATRE COMMUNITY" title="The work between the work." copy="Follow creative practice, productions, and people shaping the local stage." /><section className="post-composer"><StageAvatar initials={artist.initials}/><textarea value={draft} onChange={e => setDraft(e.target.value)} placeholder="Share a rehearsal moment, thought, or production update..." /><StageButton onClick={publish}>Publish</StageButton></section><div className="post-stack">{posts.map(post => <article className="social-post" key={post.id}><header><StageAvatar initials={post.initials}/><div><h3>{post.author}</h3><p>{post.role}  |  {post.time}</p></div><button>...</button></header><p className="post-text">{post.text}</p><div className={`post-canvas ${post.color}`}><span>STAGE / PUNE</span><strong>{post.tags[0].replace('-', ' ')}</strong></div><footer><button onClick={() => applaud(post.id)}>Applaud {post.likes}</button><button>Comment {post.comments}</button><button>Share</button></footer></article>)}</div></div> }

function Profile() { return <div className="workspace-content profile-page"><PageTitle eyebrow="ARTIST PROFILE" title={artist.name} copy={`${artist.role} based in ${artist.location}.`} action={<StageButton>Edit profile</StageButton>} /><section className="profile-hero"><div className="profile-photo">MD</div><div><span className="availability">{artist.availability}</span><h2>Acting with movement, music, and stillness.</h2><p>I make work that begins in the body. Currently collaborating across Marathi, Hindi, and English theatre.</p><div className="profile-metrics"><b>{artist.followers}<small>followers</small></b><b>{artist.following}<small>following</small></b><b>{artist.completedCredits}<small>credits</small></b></div></div></section><section className="portfolio-section"><div className="panel-heading"><div><p>SELECTED WORK</p><h2>Portfolio</h2></div><StageButton variant="secondary">Add work</StageButton></div><div className="portfolio-grid">{['A Room of Her Own', 'The Last Monsoon', 'Bodies in Transit'].map((work, index) => <article className={`portfolio-card card-${index}`} key={work}><span>{index === 0 ? '2025' : '2024'}</span><h3>{work}</h3><p>{index === 1 ? 'Rangmanch Pune' : 'Independent production'}</p></article>)}</div></section></div> }

function Search() { const [term, setTerm] = useState(''); const found = artists.filter(a => `${a.name} ${a.craft} ${a.area}`.toLowerCase().includes(term.toLowerCase())); return <div className="workspace-content"><PageTitle eyebrow="DISCOVER TALENT" title="Find your next collaborator." copy="Theatre professionals in Pune, organised around real work and trusted credits." /><div className="filter-bar"><input value={term} onChange={e => setTerm(e.target.value)} placeholder="Search by name, discipline or locality" /><button>Available now</button><button>Verified credits</button><button>Pune</button></div><div className="artist-list">{found.map(person => <article className="artist-result" key={person.name}><span className={`result-avatar ${person.color}`}>{person.initials}</span><div><h3>{person.name}</h3><p>{person.craft}  |  {person.area}</p><small>{person.languages}</small></div><strong>{person.credits}<small>credits</small></strong><StageButton variant="secondary">Follow</StageButton></article>)}</div></div> }

function Castings() { const [applied, setApplied] = useState([]); return <div className="workspace-content"><PageTitle eyebrow="PUNE CASTING CALLS" title="The right role can find you." copy="Open theatre opportunities from verified groups and casting teams." action={<NavLink to="/organization"><StageButton>Post a casting call</StageButton></NavLink>} /><div className="casting-grid">{dashboard.opportunities.map((role, index) => <article className="casting-card" key={role.id}><span className={`role-mark ${role.tone}`}>CC</span><p>CASTING CALL</p><h2>{role.title}</h2><h3>{role.company}</h3><small>{role.meta}</small><div className="casting-tags"><span>Audition: 20 Aug</span><span>{index === 0 ? 'Paid' : 'Open call'}</span></div><StageButton variant={applied.includes(role.id) ? 'secondary' : 'primary'} onClick={() => setApplied([...applied, role.id])}>{applied.includes(role.id) ? 'Application sent' : 'Apply now'}</StageButton></article>)}</div></div> }

function Applications() { return <div className="workspace-content"><PageTitle eyebrow="YOUR APPLICATIONS" title="Keep your next role in view." copy="Track every application, invitation, and audition in one place." /><div className="application-list">{dashboard.opportunities.map((role, index) => <article key={role.id}><span className={`status-dot ${index === 0 ? 'shortlisted' : index === 1 ? 'review' : 'sent'}`}></span><div><h2>{role.title}</h2><p>{role.company}  |  Applied 2 Aug</p></div><b>{index === 0 ? 'Shortlisted' : index === 1 ? 'Under review' : 'Applied'}</b><NavLink to="/messages">Message</NavLink></article>)}</div></div> }

function Messages() { const [active, setActive] = useState(conversations[0]); const [message, setMessage] = useState(''); const [thread, setThread] = useState(['Hi Maya, we loved your movement reel.', 'Would Thursday work for the reading?']); const send = () => { if (!message.trim()) return; setThread([...thread, message]); setMessage('') }; return <div className="workspace-content messages-page"><PageTitle eyebrow="MESSAGES" title="Conversations that lead to work." /><div className="messages-layout"><aside>{conversations.map(c => <button className={active.id === c.id ? 'selected' : ''} onClick={() => setActive(c)} key={c.id}><StageAvatar initials={c.initials}/><div><b>{c.name}</b><span>{c.last}</span></div>{c.unread ? <em>{c.unread}</em> : <small>{c.time}</small>}</button>)}</aside><section className="message-thread"><header><StageAvatar initials={active.initials}/><div><h3>{active.name}</h3><p>Active now</p></div></header><div className="thread-body">{thread.map((text, index) => <p className={index % 2 ? 'incoming' : 'outgoing'} key={`${text}-${index}`}>{text}</p>)}</div><form onSubmit={e => { e.preventDefault(); send() }}><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Write a message..." /><StageButton>Send</StageButton></form></section></div></div> }

function Notifications() { return <div className="workspace-content"><PageTitle eyebrow="NOTIFICATIONS" title="Stay close to the work." /><div className="notification-list">{notifications.map(([text, time, type]) => <article key={text}><span className={`notice-icon ${type}`}>{type.slice(0, 1).toUpperCase()}</span><div><p>{text}</p><small>{time}</small></div><button>Mark read</button></article>)}</div></div> }

function Organization() { const [posted, setPosted] = useState(false); return <div className="workspace-content organization-page"><PageTitle eyebrow="ORGANIZATION WORKSPACE" title="Rangmanch Pune" copy="Manage productions, discover talent, and make casting simple." action={<StageButton onClick={() => setPosted(true)}>{posted ? 'Casting published' : 'Create casting call'}</StageButton>} /><div className="org-grid"><article><p>ACTIVE CASTINGS</p><strong>4</strong><span>2 closing this week</span></article><article><p>NEW APPLICATIONS</p><strong>36</strong><span>Across 4 roles</span></article><article><p>PROFILE VIEWS</p><strong>1,248</strong><span>Up 18% this month</span></article></div><section className="workspace-panel talent-pipeline"><div className="panel-heading"><div><p>THE LAST MONSOON</p><h2>Talent pipeline</h2></div><NavLink to="/search">Discover talent</NavLink></div>{artists.map((person, i) => <article key={person.name}><StageAvatar initials={person.initials}/><div><h3>{person.name}</h3><p>{person.craft}</p></div><span>{i === 0 ? 'Shortlisted' : 'New application'}</span><StageButton variant="secondary">Message</StageButton></article>)}</section></div> }

function Settings() { const [saved, setSaved] = useState(false); return <div className="workspace-content"><PageTitle eyebrow="SETTINGS" title="Shape your Stage." copy="Control visibility, opportunity alerts, and community preferences." /><section className="settings-card"><h2>Professional preferences</h2><label><span>Profile visibility</span><select defaultValue="public"><option value="public">Visible to everyone</option><option>Only organizations</option><option>Private</option></select></label><label className="switch-row"><span>Opportunity recommendations</span><input type="checkbox" defaultChecked /></label><label className="switch-row"><span>Community activity updates</span><input type="checkbox" defaultChecked /></label><StageButton onClick={() => setSaved(true)}>{saved ? 'Preferences saved' : 'Save preferences'}</StageButton></section></div> }

export function WorkspacePage() { const { page = 'dashboard' } = useParams(); const screens = { dashboard: <Dashboard/>, feed: <Feed/>, profile: <Profile/>, search: <Search/>, castings: <Castings/>, applications: <Applications/>, messages: <Messages/>, notifications: <Notifications/>, organization: <Organization/>, settings: <Settings/> }; return <div className="workspace"><Sidebar/><div className="workspace-main"><Topbar/>{screens[page] ?? <Dashboard/>}</div></div> }
